 /******************************************************************************
 *
 * Module: LCD
 *
 * File Name: lcd.h
 *
 * Description: Header file for the LCD driver
 *
 * Author: Mohamed Ezzat
 *
 * created date : 3/10/2022
 *
 * Version : v1.0.1
 *
 *******************************************************************************/

#ifndef HCSR04_H_
#define HCSR04_H_

#include"std_types.h"
/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

/*******************************************************************************
 *                                FUNCTIONS                                  *
 *******************************************************************************/

/*
 * Description:
 * 1 - Initialize the ICU driver as required.
 * 2 - Setup the ICU call back function.
 * 3 - Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void ultrasonic_init(void);

/*
 * Description :
 * 1 - Send the Trigger pulse to the ultrasonic.
 */
void ultrasonic_Trigger(void);

/*
 * Description :
 * 1 - Send the trigger pulse by using Ultrasonic_Trigger function
 * 2 - Start the measurements by the ICU from this moment
 */
uint16 ultrasonic_readDistance(void);

/*
 * Description :
 * 1 - This is the call back function called by the ICU driver
 * 2 - This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void ultrasonic_edgeProcessing(void);

#endif /* HCSR04_H_ */
